package com.example.orbisapp.ui.theme

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.orbisapp.model.QAPair
import com.example.orbisapp.network.RetrofitClient
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch

class QAViewModel : ViewModel() {

    private val _pairs = MutableStateFlow<List<QAPair>>(emptyList())
    val pairs: StateFlow<List<QAPair>> = _pairs

    private val _error = MutableStateFlow<String?>(null)
    val error: StateFlow<String?> = _error

    private val _loading = MutableStateFlow(false)
    val loading: StateFlow<Boolean> = _loading

    init {
        loadAll()
    }

    fun loadAll() {
        viewModelScope.launch {
            _loading.value = true
            _error.value = null
            try {
                _pairs.value = RetrofitClient.api.getAll()
            } catch (e: Exception) {
                _error.value = e.message
            } finally {
                _loading.value = false
            }
        }
    }

    fun addPair(question: String, answer: String) {
        viewModelScope.launch {
            _loading.value = true
            try {
                // Assuming ID is generated by server, using empty string for now
                // if the API requires a QAPair object.
                val newPair = QAPair(id = "", question = question, answer = answer)
                RetrofitClient.api.create(newPair)
                loadAll() // Refresh the list
            } catch (e: Exception) {
                _error.value = e.message
            } finally {
                _loading.value = false
            }
        }
    }
}